ALTER TABLE "accounts"
  ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3);

ALTER TABLE "orders"
  ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'YER',
  ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "pricesVisible" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "priceAcceptedAt" TIMESTAMP(3);

ALTER TABLE "transactions"
  ADD COLUMN IF NOT EXISTS "voucherNumber" TEXT,
  ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'YER',
  ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "attachmentUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "balanceAfter" DECIMAL(15, 2);

CREATE UNIQUE INDEX IF NOT EXISTS "transactions_voucherNumber_key"
  ON "transactions"("voucherNumber");
